#' Classify hematopoietic vs non-hematopoietic cells
#'
#' A prefiltering step to remove hematopoietic cells based on an integrated
#' dataset R1 consisting of whole bone marrow, hematopoietic stem and progenitor
#' cells, and central marrow and endosteal stromal cells.
#'
#' @param query Seurat object to annotate
#' @param ref Seurat reference object containing PCA reduction and `nonhematopoietic` metadata
#' @param return.seurat Logical. If TRUE, returns Seurat object with predictions added; otherwise, return prediction table. (Default: FALSE)
#'
#' @return Either Seurat object or TransferData output
#'
#' @details
#' Uses Seurat label transfer (FindTransferAnchors + TransferData)
#' based on PCA space from the reference.
#'
#' @export
classify_hematopoietic <- function(query, ref, return.seurat=FALSE) {
  stopifnot("nonhematopoietic" %in% colnames(ref@meta.data))
  rlang::inform("Finding transfer anchors.")
  anchors <- Seurat::FindTransferAnchors(reference=ref, query=query, dims=1:30, reference.reduction="pca", features=ref@misc$bm.var_genes, verbose=FALSE)
  rlang::inform("Classifying nonhematopoietic cells.")
  preds <- Seurat::TransferData(anchorset=anchors, refdata=ref$nonhematopoietic, verbose=FALSE)
  if (return.seurat) {
    query$nonhematopoietic_pred <- as.factor(preds$predicted.id)
    query$nonhematopoietic_pred_score <- preds$prediction.score.max
    return(query)
  } else {
    return(list(preds=preds, anchors=anchors))
  }
}

#' Classify stroma cell types
#'
#' Performs non-hematopoietic cell annotation based on two references.
#' Reference R2.1 is generated by barcoding 10 FACS-purified populations of
#' stromal cells using on-chip multiplexing before sequencing. Reference R2.2 is
#' generated by curating key marker genes for stromal cell types.
#'
#' @param query Seurat object to annotate (typically stromal subset)
#' @param ref Stromal reference Seurat object containing PCA reduction and `nonhematopoietic` metadata
#' @param return.seurat Logical. If TRUE, returns Seurat object with predictions added; otherwise, return prediction table. (Default: FALSE)
#'
#' @return Either Seurat object or list of TransferData output
#'
#' @details
#' Uses Seurat label transfer (FindTransferAnchors + TransferData)
#' based on PCA space from the reference. Transfers two sets of annotations: hash_label and manual_annot.
#'
#' @export
classify_stroma <- function(query, ref, return.seurat=FALSE) {
  stopifnot(all(c("hash_label", "manual_annot") %in% colnames(ref@meta.data)))
  rlang::inform("Finding new transfer anchors.")
  ref.hash_label <- subset(ref, cells=SeuratObject::Cells(ref)[!is.na(ref$hash_label)])
  anchors.hash_label <- Seurat::FindTransferAnchors(reference=ref.hash_label, query=query, dims=1:30, reference.reduction="pca", features=ref@misc$stroma.var_genes, verbose=FALSE)
  ref.manual_annot <- subset(ref, cells=SeuratObject::Cells(ref)[!is.na(ref$manual_annot)])
  anchors.manual_annot <- Seurat::FindTransferAnchors(reference=ref.manual_annot, query=query, dims=1:30, reference.reduction="pca", features=ref@misc$stroma.var_genes, verbose=FALSE)
  rlang::inform("Classifying stromal cell types.")
  preds.hash_label <- Seurat::TransferData(anchorset=anchors.hash_label, refdata=ref.hash_label$hash_label, verbose=FALSE)
  preds.manual_annot <- Seurat::TransferData(anchorset=anchors.manual_annot, refdata=ref.manual_annot$manual_annot, verbose=FALSE)

  if (return.seurat) {
    query$hash_label_pred <- preds.hash_label$predicted.id
    query$hash_label_pred_score <- preds.hash_label$prediction.score.max
    query$manual_annot_pred <- preds.manual_annot$predicted.id
    query$manual_annot_pred_score <- preds.manual_annot$prediction.score.max
    return(query)
  } else {
    return(list(preds.hash_label=preds.hash_label, preds.manual_annot=preds.manual_annot, anchors=anchors.manual_annot))
  }
}

#' iMSC-L scoring
#'
#' Computes a iMSC-L score based on a list of 100 genes upregulated in
#' pIC-injected MSC-L, CM_MSCL, Endo_MSCL, CM_iMSCL, and Endo_iMSCL using UCell.
#'
#' @param query Seurat object to score (typically MSC-Ls).
#' @param genes List of 100 genes for iMSC_L score
#'
#' @return Matrix with UCell scores.
#'
#' @export
score_imscl_ucell <- function(query, genes) {
  rlang::inform("Computing iMSC-L scores.")
  query <- UCell::AddModuleScore_UCell(query, features=genes, name="iMSCL")
  scores <- data.frame(iMSCL_score=query$signature_1iMSCL, row.names=SeuratObject::Cells(query))

  return(scores)
}

#' NicheScribe annotation pipeline
#'
#' Runs hierarchical label transfer and iMSC-L scoring:
#' 1. Hematopoietic vs non-hematopoietic classification
#' 2. Stromal subtype classification for non-hematopoietic cells
#' 3. iMSC-L scoring for MSC-L cells
#'
#' @param query Seurat object to annotate
#' @param do_normalize Logical. If TRUE, runs NormalizeData on query.
#' @param do_umap Logical. If TRUE, projects onto reference UMAP.
#'
#' @return Seurat object with added prediction metadata columns
#'
#' @export
NicheScribe <- function(query, do_normalize=TRUE, do_umap=TRUE) {
  if (!all(c("R1", "R2", "imscl_genes", "umap_model") %in% ls(NicheScribeData))) {
    get_data()
  }

  if (do_normalize) {
    rlang::inform("Normalizing query.")
    query <- Seurat::NormalizeData(query, verbose=FALSE)
  }

  hem.preds <- classify_hematopoietic(query, ref=NicheScribeData$R1, return.seurat=FALSE)
  query$nonhematopoietic_pred <- hem.preds$preds$predicted.id
  query$nonhematopoietic_pred_score <- hem.preds$preds$prediction.score.max

  query.nonhem <- subset(query, cells=SeuratObject::Cells(query)[query$nonhematopoietic_pred == "nonhematopoietic"])
  stroma.preds <- classify_stroma(query.nonhem, ref=NicheScribeData$R2, return.seurat=FALSE)

  query$hash_label_pred <- NA_character_
  query$hash_label_pred_score <- NA_real_
  query$manual_annot_pred <- NA_character_
  query$manual_annot_pred_score <- NA_real_
  query$hash_label_pred[rownames(stroma.preds$preds.hash_label)] <- stroma.preds$preds.hash_label$predicted.id
  query$hash_label_pred_score[rownames(stroma.preds$preds.hash_label)] <- stroma.preds$preds.hash_label$prediction.score.max
  query$manual_annot_pred[rownames(stroma.preds$preds.manual_annot)] <- stroma.preds$preds.manual_annot$predicted.id
  query$manual_annot_pred_score[rownames(stroma.preds$preds.manual_annot)] <- stroma.preds$preds.manual_annot$prediction.score.max

  query.mscl <- subset(query, cells=SeuratObject::Cells(query)[query$hash_label_pred %in% c("CM_MSCL", "Endo_MSCL") | query$manual_annot_pred %in% c("CM_MSCL", "Endo_MSCL")])
  imscl.scores <- score_imscl_ucell(query.mscl, genes=NicheScribeData$imscl_genes)

  query$iMSCL_score <- NA_real_
  query$iMSCL_score[rownames(imscl.scores)] <- imscl.scores$iMSCL_score

  # Seurat::IntegrateEmbeddings occasionally causes an error with
  # future.globals.maxSize. This happens if reuse.weights.matrix=FALSE or
  # verbose=FALSE, paradoxically.
  if (do_umap) {
    rlang::inform("Running UMAP")

    withr::local_options(list(future.globals.maxSize = 2 * 1024^3))
    query.nonhem <- withCallingHandlers(
      Seurat::IntegrateEmbeddings(
        anchorset=stroma.preds$anchors,
        reference=NicheScribeData$R2,
        query=query.nonhem,
        new.reduction.name="ref.pca",
        reuse.weights.matrix=TRUE,
        verbose=FALSE
      ),
      warning = function(w) {
        if (grepl("Layer counts isn't present", conditionMessage(w))) {
          invokeRestart("muffleWarning")
        } else {
          warning(w)
        }
      },
      message = function(m) {
        if (grepl("Requested to reuse weights matrix", conditionMessage(m))) {
          invokeRestart("muffleMessage")
        } else {
          message(m)
        }
      }
    )

    umap_query <- uwot::umap_transform(SeuratObject::Embeddings(query.nonhem, "ref.pca")[,1:15], NicheScribeData$umap_model)

    colnames(umap_query) <- c("UMAP1", "UMAP2")

    full_umap <- matrix(
      NA_real_,
      nrow=length(SeuratObject::Cells(query)),
      ncol=ncol(umap_query),
      dimnames=list(SeuratObject::Cells(query), colnames(umap_query))
    )
    common <- intersect(SeuratObject::Cells(query), rownames(umap_query))
    full_umap[common,] <- umap_query[common,]

    query[["nichescribe_umap"]] <- Seurat::CreateDimReducObject(
      embeddings=full_umap,
      assay=SeuratObject::DefaultAssay(query),
      key="nichescribeumap_"
    )
  }

  return(query)
}
